// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebNDTIT01.Models;

namespace WebNDTIT01.Migrations
{
    [DbContext(typeof(ndt_dbContext))]
    partial class ndt_dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("WebNDTIT01.Models.TbComputerAssetNo", b =>
                {
                    b.Property<int>("IdComputerAssetNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AssetNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ComputerName")
                        .HasColumnType("longtext");

                    b.HasKey("IdComputerAssetNo");

                    b.ToTable("TbComputerAssetNo");
                });

            modelBuilder.Entity("WebNDTIT01.Models.TbComputerList", b =>
                {
                    b.Property<int>("IdcomputerList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AssetNo")
                        .HasColumnType("int");

                    b.Property<string>("ComManufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("ComModel")
                        .HasColumnType("longtext");

                    b.Property<string>("ComSerialNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ComputerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CpuModel")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Domain")
                        .HasColumnType("longtext");

                    b.Property<string>("Ipadds")
                        .HasColumnType("longtext");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("MacAdds")
                        .HasColumnType("longtext");

                    b.Property<int?>("MonitorId")
                        .HasColumnType("int");

                    b.Property<string>("Nictype")
                        .HasColumnType("longtext");

                    b.Property<string>("Os")
                        .HasColumnType("longtext");

                    b.Property<string>("Ostype")
                        .HasColumnType("longtext");

                    b.Property<int?>("Ramsize")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IdcomputerList");

                    b.ToTable("TbComputerList");
                });

            modelBuilder.Entity("WebNDTIT01.Models.TbMonitorList", b =>
                {
                    b.Property<int>("IdMonitorList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("MonitorAsset")
                        .HasColumnType("int");

                    b.Property<string>("MonitorManufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("MonitorModel")
                        .HasColumnType("longtext");

                    b.Property<string>("MonitorSerialNo")
                        .HasColumnType("longtext");

                    b.HasKey("IdMonitorList");

                    b.ToTable("tbMonitorList");
                });

            modelBuilder.Entity("WebNDTIT01.Models.TbUser", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserLastname")
                        .HasColumnType("longtext");

                    b.Property<string>("UserLogin")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("IdUser");

                    b.ToTable("tbUser");
                });
#pragma warning restore 612, 618
        }
    }
}
